[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["aqmlator", "qbm4eo"]
module-root = ""

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.uv.sources]
qmetric = { git = "ssh://git@gitlab.com/illesova.silvie.scholar/qmetric.git" }

[tool.deptry.package_module_name_map]
fastapi = "fastapi"
ruff = "ruff"
dill = "dill"
dwave-ocean-sdk = "dimod"
scikit-learn = "sklearn"
tqdm = "tqdm"
psycopg2 = "psycopg2"
optuna = "optuna"
requests = "requests"
torch = "torch"
lightning = "lightning"
numpy = "numpy"
pennylane = "pennylane"
pennylane-lightning = "pennylane_lightning"
qiskit = "qiskit"
qmetric = "qmetric"
pennylane-qiskit = "pennylane_qiskit"
qiskit-aer = "qiskit_aer"
scipy = "scipy"
coverage = "coverage"


[tool.deptry.per_rule_ignores]
DEP002 = ["ruff", "dill", "psycopg2", "pennylane-lightning", "qiskit-aer"]


[tool.ruff]
line-length = 120


[project]
name = "AQMLator"
version = "1.1.0"
authors = [
    {name="Tomasz Rybotycki", email="rybotycki.tomasz+aqmlator@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
description="A package for auto quantum machine learning-izing your experiments!"
dependencies = [
    "dill>=0.4.0",
    "dwave-ocean-sdk>=9.2.0",
    "lightning[extra]>=2.6.0",
    "numpy==2.3",
    "optuna>=4.6.0",
    "pennylane>=0.43.1",
    "pennylane-lightning>=0.43.0",
    "pennylane-qiskit==0.43.0",
    "psycopg2>=2.9.11",
    "qiskit==2.1.0",
    "qiskit-aer>=0.17.2",
    "qmetric",
    "ruff>=0.14.9",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
classifiers=[
        "Programming Language :: Python :: 3",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Physics",
]
license="Apache-2.0"

[project.urls]
documentation = "https://aqmlator.readthedocs.io/en/latest/index.html"
repository = "https://github.com/Tomev/AQMLator"

[dependency-groups]
dev = [
    "coverage>=7.13.4",
    "deptry>=0.24.0",
    "ruff>=0.14.10",
]
