[tox]
envlist = py313

[pylint]
ignore = .pylintrc
disable = .pylintrc

[testenv]
runner = uv-venv-lock-runner
passenv = aqmlator_database_url
whitelist_externals = git
allowlist_externals = mypy, pylint, deptry
commands =
	uvx deptry --version 
	uvx deptry .
	uvx ruff --version
	uvx ruff check 
	uvx mypy --version
	uvx mypy aqmlator tests qbm4eo
	uvx pylint --version
	uvx pylint --rcfile=.pylintrc --disable=E,C0103,C0301 .pylintrc aqmlator tests qbm4eo
	uv run coverage --version
	uv run coverage run -m unittest tests.test_database -v 
	uv run coverage run -m unittest tests.test_tuner -v 
	uv run coverage run -m unittest tests.test_qml -v
	uv run coverage run -m unittest tests.qbm4eo.test_rbm -v 

[testenv:full]
passenv = IBMQ_TOKEN, IBMQ_CRN, aqmlator_database_url
runner = uv-venv-lock-runner
whitelist_externals = git
allowlist_externals = mypy, pylint, deptry
commands =
	uvx deptry --version 
	uvx deptry .
	uvx ruff --version
	uvx ruff check 
	uvx mypy --version
	uvx mypy aqmlator tests qbm4eo
	uvx pylint --version
	uvx pylint --rcfile=.pylintrc --disable=E,C0103,C0301 .pylintrc aqmlator tests qbm4eo
	uv run coverage --version
	uv run coverage run -m unittest tests.test_database -v 
	uv run coverage run -m unittest tests.test_tuner -v 
	uv run coverage run -m unittest tests.test_qml -v
	uv run coverage run -m unittest tests.qbm4eo.test_rbm -v 
	uv run coverage run -m unittest tests.test_qml_ibm -v  # Additional, long test.



[tox:.package]
basepython = python3
